import re
import ast
from typing import Dict, List, Any, Tuple, Optional
from datetime import datetime
import json
import numpy as np
from typing_extensions import Optional
import warnings
warnings.filterwarnings('ignore')

# NLP and AI imports
try:
    from sentence_transformers import SentenceTransformer
    from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification
    import spacy
    import wikipediaapi
    import torch
    from sklearn.metrics.pairwise import cosine_similarity
    from sklearn.feature_extraction.text import TfidfVectorizer
    SBERT_AVAILABLE = True
    SPACY_AVAILABLE = True
    TRANSFORMERS_AVAILABLE = True
    WIKIPEDIA_AVAILABLE = True
except ImportError as e:
    print(f"Warning: Some AI dependencies not available: {e}")
    SBERT_AVAILABLE = False
    SPACY_AVAILABLE = False
    TRANSFORMERS_AVAILABLE = False
    WIKIPEDIA_AVAILABLE = False

class AIGeneratedCodeDetector:
    def __init__(self):
        self.ai_patterns = {
            'placeholder_comments': [
                r'# TODO:.*',
                r'# FIXME:.*',
                r'# Insert.*here',
                r'# Add.*here',
                r'# Implement.*here',
                r'# Placeholder',
                r'// TODO:.*',
                r'// FIXME:.*',
                r'// Insert.*here',
                r'// Add.*here',
                r'// Implement.*here',
                r'// Placeholder',
                r'/\* TODO:.*?\*/',
                r'/\* FIXME:.*?\*/',
                r'/\* Insert.*?\*/',
                r'/\* Add.*?\*/',
                r'/\* Implement.*?\*/',
                r'/\* Placeholder.*?\*/'
            ],
            'generic_variable_names': [
                r'\bvar\s+[a-z]\b',
                r'\blet\s+[a-z]\b',
                r'\bconst\s+[a-z]\b',
                r'\b[a-z]\s*=\s*[^;]+',
                r'\b[a-z]\s*:\s*[^;]+',
                r'\b[a-z]\s*=\s*[^;]+',
                r'\b[a-z]\s*:\s*[^;]+'
            ],
            'ai_generated_markers': [
                r'Generated by AI',
                r'AI-generated',
                r'Model: GPT',
                r'AI completion',
                r'Generated by ChatGPT',
                r'Generated by Claude',
                r'Generated by Copilot',
                r'AI assistant',
                r'Generated by',
                r'This code was generated'
            ],
            'overly_generic_comments': [
                r'# This function',
                r'# This method',
                r'# This class',
                r'# This variable',
                r'// This function',
                r'// This method',
                r'// This class',
                r'// This variable'
            ]
        }
        
        self.descriptive_comment_patterns = [
            r'# [A-Z][^.]*\.',  # Comments that start with capital and end with period
            r'// [A-Z][^.]*\.',
            r'/\* [A-Z][^.]*\.',
            r'# [A-Z][^.]*:',   # Comments that start with capital and end with colon
            r'// [A-Z][^.]*:',
            r'/\* [A-Z][^.]*:'
        ]

        # Initialize AI models
        self._initialize_ai_models()
        
        # Knowledge base for semantic analysis
        self.knowledge_base = self._build_knowledge_base()

    def _initialize_ai_models(self):
        """Initialize SBERT, spaCy, and local LLM models"""
        try:
            # Initialize SBERT for semantic similarity
            if SBERT_AVAILABLE:
                self.sbert_model = SentenceTransformer('all-MiniLM-L6-v2')
                print("✓ SBERT model loaded successfully")
            else:
                self.sbert_model = None
                print("✗ SBERT not available")

            # Initialize spaCy for NLP analysis
            if SPACY_AVAILABLE:
                try:
                    self.nlp = spacy.load("en_core_web_sm")
                except OSError:
                    print("Downloading spaCy model...")
                    spacy.cli.download("en_core_web_sm")
                    self.nlp = spacy.load("en_core_web_sm")
                print("✓ spaCy model loaded successfully")
            else:
                self.nlp = None
                print("✗ spaCy not available")

            # Initialize local LLM for text classification
            if TRANSFORMERS_AVAILABLE:
                try:
                    # Use a smaller model for local inference
                    self.text_classifier = pipeline(
                        "text-classification",
                        model="distilbert-base-uncased",
                        return_all_scores=True
                    )
                    print("✓ Local LLM model loaded successfully")
                except Exception as e:
                    print(f"✗ Local LLM not available: {e}")
                    self.text_classifier = None
            else:
                self.text_classifier = None
                print("✗ Transformers not available")

            # Initialize Wikipedia API
            if WIKIPEDIA_AVAILABLE:
                self.wiki = wikipediaapi.Wikipedia('en')
                print("✓ Wikipedia API initialized")
            else:
                self.wiki = None
                print("✗ Wikipedia API not available")

        except Exception as e:
            print(f"Error initializing AI models: {e}")
            self.sbert_model = None
            self.nlp = None
            self.text_classifier = None
            self.wiki = None

    def _build_knowledge_base(self) -> Dict[str, List[str]]:
        """Build a knowledge base of programming concepts and patterns"""
        knowledge_base = {
            'programming_concepts': [
                'algorithm', 'data structure', 'function', 'class', 'object',
                'inheritance', 'polymorphism', 'encapsulation', 'abstraction',
                'recursion', 'iteration', 'sorting', 'searching', 'optimization',
                'memory management', 'garbage collection', 'threading', 'asynchronous',
                'database', 'API', 'REST', 'GraphQL', 'authentication', 'authorization'
            ],
            'code_quality_patterns': [
                'clean code', 'SOLID principles', 'DRY principle', 'KISS principle',
                'code review', 'unit testing', 'integration testing', 'refactoring',
                'design patterns', 'anti-patterns', 'technical debt', 'maintainability',
                'readability', 'performance', 'security', 'scalability'
            ],
            'ai_generated_indicators': [
                'placeholder', 'TODO', 'FIXME', 'implement', 'add logic',
                'generic variable', 'temporary name', 'sample code', 'example',
                'template', 'boilerplate', 'stub', 'skeleton'
            ]
        }
        return knowledge_base

    def detect_ai_generated_code(self, code: str, language: str, edit_history: Optional[List[Dict]] = None) -> Dict[str, Any]:
        """
        Enhanced AI-generated code detection using multiple AI models
        """
        issues = []
        ai_score = 0.0
        total_checks = 0
        
        # Traditional pattern-based checks
        placeholder_issues = self._check_placeholder_comments(code, language)
        issues.extend(placeholder_issues)
        ai_score += len(placeholder_issues) * 0.3
        total_checks += 1
        
        variable_issues = self._check_generic_variable_names(code, language)
        issues.extend(variable_issues)
        ai_score += len(variable_issues) * 0.2
        total_checks += 1
        
        comment_issues = self._check_descriptive_comments(code, language)
        issues.extend(comment_issues)
        ai_score += len(comment_issues) * 0.25
        total_checks += 1
        
        marker_issues = self._check_ai_markers(code)
        issues.extend(marker_issues)
        ai_score += len(marker_issues) * 0.5
        total_checks += 1
        
        if edit_history:
            timing_issues = self._check_code_timing(edit_history)
            issues.extend(timing_issues)
            ai_score += len(timing_issues) * 0.4
            total_checks += 1
        
        generic_comment_issues = self._check_generic_comments(code, language)
        issues.extend(generic_comment_issues)
        ai_score += len(generic_comment_issues) * 0.15
        total_checks += 1

        # AI-powered semantic analysis
        semantic_issues = self._semantic_analysis(code, language)
        issues.extend(semantic_issues)
        ai_score += len(semantic_issues) * 0.4
        total_checks += 1

        # NLP-based comment analysis
        nlp_issues = self._nlp_comment_analysis(code, language)
        issues.extend(nlp_issues)
        ai_score += len(nlp_issues) * 0.35
        total_checks += 1

        # Local LLM classification
        llm_score = self._llm_classification(code, language)
        ai_score += llm_score * 0.6
        total_checks += 1

        # Knowledge base verification
        knowledge_issues = self._knowledge_base_verification(code, language)
        issues.extend(knowledge_issues)
        ai_score += len(knowledge_issues) * 0.3
        total_checks += 1

        # Wikipedia-based concept validation
        wiki_issues = self._wikipedia_concept_validation(code, language)
        issues.extend(wiki_issues)
        ai_score += len(wiki_issues) * 0.25
        total_checks += 1
        
        # Normalize AI score
        normalized_score = min(1.0, ai_score / max(total_checks, 1))
        
        return {
            "ai_detected": normalized_score > 0.3,
            "ai_confidence": normalized_score,
            "issues": issues,
            "suggestions": self._generate_suggestions(issues, normalized_score),
            "fixes": self._generate_fixes(code, issues, language),
            "ai_analysis": {
                "semantic_score": self._get_semantic_score(semantic_issues),
                "nlp_score": self._get_nlp_score(nlp_issues),
                "llm_score": llm_score,
                "knowledge_score": self._get_knowledge_score(knowledge_issues),
                "wiki_score": self._get_wiki_score(wiki_issues)
            }
        }

    def _semantic_analysis(self, code: str, language: str) -> List[Dict]:
        """Use SBERT for semantic similarity analysis of comments and code"""
        issues = []
        
        if not self.sbert_model:
            return issues

        try:
            # Extract comments from code
            comments = self._extract_comments(code, language)
            if not comments:
                return issues

            # Get embeddings for comments
            comment_embeddings = self.sbert_model.encode(comments)
            
            # Compare with known AI-generated comment patterns
            ai_comment_patterns = [
                "This function does something",
                "This method performs an operation",
                "This class represents a data structure",
                "This variable stores a value",
                "Add implementation here",
                "Insert logic here",
                "TODO: implement this",
                "Placeholder for future implementation"
            ]
            
            pattern_embeddings = self.sbert_model.encode(ai_comment_patterns)
            
            # Calculate similarities
            similarities = cosine_similarity(comment_embeddings, pattern_embeddings)
            
            for i, comment in enumerate(comments):
                max_similarity = np.max(similarities[i])
                if max_similarity > 0.8:  # High similarity threshold
                    issues.append({
                        "type": "semantic_similarity",
                        "message": f"Comment shows high similarity to AI-generated patterns: '{comment}'",
                        "line": self._find_comment_line(code, comment),
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Rewrite comment to be more specific and descriptive",
                        "fix": self._generate_semantic_fix(comment, language),
                        "confidence": max_similarity
                    })
        
        except Exception as e:
            print(f"Semantic analysis error: {e}")
        
        return issues

    def _nlp_comment_analysis(self, code: str, language: str) -> List[Dict]:
        """Use spaCy for advanced NLP analysis of comments"""
        issues = []
        
        if not self.nlp:
            return issues

        try:
            comments = self._extract_comments(code, language)
            
            for comment in comments:
                doc = self.nlp(comment)
                
                # Check for overly generic language
                generic_indicators = ['this', 'that', 'thing', 'stuff', 'something', 'anything']
                generic_count = sum(1 for token in doc if token.text.lower() in generic_indicators)
                
                if generic_count > 2:
                    issues.append({
                        "type": "generic_language",
                        "message": f"Comment uses overly generic language: '{comment}'",
                        "line": self._find_comment_line(code, comment),
                        "severity": "low",
                        "category": "ai_generated",
                        "suggestion": "Use more specific and descriptive language",
                        "fix": self._generate_nlp_fix(comment, language)
                    })
                
                # Check for lack of technical terms
                technical_terms = [token.text for token in doc if token.pos_ in ['NOUN', 'PROPN']]
                if len(technical_terms) < 2:
                    issues.append({
                        "type": "lack_technical_terms",
                        "message": f"Comment lacks technical specificity: '{comment}'",
                        "line": self._find_comment_line(code, comment),
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Include more technical terms and specific details",
                        "fix": self._generate_technical_fix(comment, language)
                    })
        
        except Exception as e:
            print(f"NLP analysis error: {e}")
        
        return issues

    def _llm_classification(self, code: str, language: str) -> float:
        """Use local LLM for text classification of code comments"""
        if not self.text_classifier:
            return 0.0

        try:
            # Extract and combine comments
            comments = self._extract_comments(code, language)
            if not comments:
                return 0.0
            
            combined_text = " ".join(comments)
            
            # Classify the text
            results = self.text_classifier(combined_text)
            
            # Calculate AI probability (simplified approach)
            # In practice, you'd train a custom model for this specific task
            ai_probability = 0.0
            
            # Simple heuristic based on text characteristics
            if len(combined_text) > 0:
                generic_words = ['this', 'that', 'thing', 'stuff', 'something', 'anything', 'TODO', 'FIXME']
                generic_count = sum(1 for word in generic_words if word.lower() in combined_text.lower())
                ai_probability = min(1.0, generic_count / len(combined_text.split()) * 10)
            
            return ai_probability
        
        except Exception as e:
            print(f"LLM classification error: {e}")
            return 0.0

    def _knowledge_base_verification(self, code: str, language: str) -> List[Dict]:
        """Verify code against programming knowledge base"""
        issues = []
        
        try:
            # Extract function and class names
            function_names = self._extract_function_names(code, language)
            class_names = self._extract_class_names(code, language)
            
            # Check against knowledge base
            for func_name in function_names:
                if not self._is_meaningful_name(func_name):
                    issues.append({
                        "type": "meaningless_function_name",
                        "message": f"Function name '{func_name}' lacks meaning",
                        "line": self._find_function_line(code, func_name),
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Use descriptive function names that indicate purpose",
                        "fix": self._generate_meaningful_name_fix(func_name, language)
                    })
            
            for class_name in class_names:
                if not self._is_meaningful_name(class_name):
                    issues.append({
                        "type": "meaningless_class_name",
                        "message": f"Class name '{class_name}' lacks meaning",
                        "line": self._find_class_line(code, class_name),
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Use descriptive class names that indicate purpose",
                        "fix": self._generate_meaningful_name_fix(class_name, language)
                    })
        
        except Exception as e:
            print(f"Knowledge base verification error: {e}")
        
        return issues

    def _wikipedia_concept_validation(self, code: str, language: str) -> List[Dict]:
        """Validate programming concepts against Wikipedia"""
        issues = []
        
        if not self.wiki:
            return issues

        try:
            # Extract technical terms from comments
            comments = self._extract_comments(code, language)
            technical_terms = []
            
            for comment in comments:
                if self.nlp:
                    doc = self.nlp(comment)
                    technical_terms.extend([token.text for token in doc if token.pos_ in ['NOUN', 'PROPN']])
            
            # Check if terms are valid programming concepts
            for term in set(technical_terms):
                if len(term) > 3:  # Only check meaningful terms
                    page = self.wiki.page(term)
                    if not page.exists():
                        issues.append({
                            "type": "invalid_technical_term",
                            "message": f"Technical term '{term}' not found in knowledge base",
                            "line": 1,
                            "severity": "low",
                            "category": "ai_generated",
                            "suggestion": "Verify technical terms and use standard terminology",
                            "fix": f"Replace '{term}' with appropriate technical term"
                        })
        
        except Exception as e:
            print(f"Wikipedia validation error: {e}")
        
        return issues

    # Helper methods for enhanced analysis
    def _extract_comments(self, code: str, language: str) -> List[str]:
        """Extract comments from code"""
        comments = []
        lines = code.split('\n')
        
        for line in lines:
            stripped = line.strip()
            if language == 'python':
                if stripped.startswith('#'):
                    comments.append(stripped[1:].strip())
            elif language in ['javascript', 'typescript']:
                if stripped.startswith('//'):
                    comments.append(stripped[2:].strip())
                elif stripped.startswith('/*') and stripped.endswith('*/'):
                    comments.append(stripped[2:-2].strip())
        
        return comments

    def _find_comment_line(self, code: str, comment: str) -> int:
        """Find the line number of a specific comment"""
        lines = code.split('\n')
        for i, line in enumerate(lines, 1):
            if comment in line:
                return i
        return 1

    def _extract_function_names(self, code: str, language: str) -> List[str]:
        """Extract function names from code"""
        function_names = []
        
        if language == 'python':
            pattern = r'def\s+(\w+)'
        elif language in ['javascript', 'typescript']:
            pattern = r'function\s+(\w+)|(\w+)\s*[:=]\s*function|(\w+)\s*[:=]\s*\([^)]*\)\s*=>'
        else:
            pattern = r'function\s+(\w+)'
        
        matches = re.finditer(pattern, code)
        for match in matches:
            function_names.append(match.group(1) or match.group(2) or match.group(3))
        
        return function_names

    def _extract_class_names(self, code: str, language: str) -> List[str]:
        """Extract class names from code"""
        class_names = []
        
        if language == 'python':
            pattern = r'class\s+(\w+)'
        elif language in ['javascript', 'typescript']:
            pattern = r'class\s+(\w+)'
        else:
            pattern = r'class\s+(\w+)'
        
        matches = re.finditer(pattern, code)
        for match in matches:
            class_names.append(match.group(1))
        
        return class_names

    def _is_meaningful_name(self, name: str) -> bool:
        """Check if a name is meaningful"""
        if len(name) < 3:
            return False
        
        # Check if it contains meaningful words
        meaningful_words = ['get', 'set', 'add', 'remove', 'create', 'delete', 'update', 'find', 'search', 'sort', 'filter', 'validate', 'process', 'handle', 'manage', 'calculate', 'compute', 'parse', 'format', 'convert', 'transform']
        
        name_lower = name.lower()
        return any(word in name_lower for word in meaningful_words)

    def _find_function_line(self, code: str, func_name: str) -> int:
        """Find the line number of a function"""
        lines = code.split('\n')
        for i, line in enumerate(lines, 1):
            if f'def {func_name}' in line or f'function {func_name}' in line:
                return i
        return 1

    def _find_class_line(self, code: str, class_name: str) -> int:
        """Find the line number of a class"""
        lines = code.split('\n')
        for i, line in enumerate(lines, 1):
            if f'class {class_name}' in line:
                return i
        return 1

    # Scoring methods
    def _get_semantic_score(self, issues: List[Dict]) -> float:
        """Calculate semantic analysis score"""
        if not issues:
            return 0.0
        return sum(issue.get('confidence', 0.5) for issue in issues) / len(issues)

    def _get_nlp_score(self, issues: List[Dict]) -> float:
        """Calculate NLP analysis score"""
        return len(issues) * 0.3

    def _get_knowledge_score(self, issues: List[Dict]) -> float:
        """Calculate knowledge base score"""
        return len(issues) * 0.25

    def _get_wiki_score(self, issues: List[Dict]) -> float:
        """Calculate Wikipedia validation score"""
        return len(issues) * 0.2

    # Fix generation methods
    def _generate_semantic_fix(self, comment: str, language: str) -> str:
        """Generate fix for semantic similarity issues"""
        if language == 'python':
            return f"# {comment.replace('This function', 'This function specifically').replace('This method', 'This method specifically')}"
        else:
            return f"// {comment.replace('This function', 'This function specifically').replace('This method', 'This method specifically')}"

    def _generate_nlp_fix(self, comment: str, language: str) -> str:
        """Generate fix for NLP issues"""
        improved = comment.replace('this thing', 'the data structure').replace('that stuff', 'the configuration').replace('something', 'the result')
        if language == 'python':
            return f"# {improved}"
        else:
            return f"// {improved}"

    def _generate_technical_fix(self, comment: str, language: str) -> str:
        """Generate fix for lack of technical terms"""
        improved = f"Processes {comment.lower()} using appropriate algorithms and data structures"
        if language == 'python':
            return f"# {improved}"
        else:
            return f"// {improved}"

    def _generate_meaningful_name_fix(self, name: str, language: str) -> str:
        """Generate fix for meaningless names"""
        if 'data' in name.lower():
            return name.replace(name, f"process{name.title()}")
        elif 'temp' in name.lower():
            return name.replace(name, f"calculate{name.title()}")
        else:
            return f"handle{name.title()}"

    # Original methods (keeping for compatibility)
    def _check_placeholder_comments(self, code: str, language: str) -> List[Dict]:
        """Check for placeholder comments that indicate incomplete AI-generated code"""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            for pattern in self.ai_patterns['placeholder_comments']:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "placeholder_comment",
                        "message": f"Placeholder comment detected: '{line.strip()}' - This suggests incomplete AI-generated code",
                        "line": line_num,
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Replace placeholder with actual implementation or remove if not needed",
                        "fix": self._generate_placeholder_fix(line, language)
                    })
                    break
        
        return issues

    def _check_generic_variable_names(self, code: str, language: str) -> List[Dict]:
        """Check for overly generic variable names"""
        issues = []
        lines = code.split('\n')
        
        # Language-specific patterns
        if language in ['javascript', 'typescript']:
            var_patterns = [
                r'\b(?:var|let|const)\s+([a-z])\b',
                r'\b([a-z])\s*[:=]\s*[^;]+',
                r'function\s+([a-z])\s*\(',
                r'const\s+([a-z])\s*='
            ]
        elif language == 'python':
            var_patterns = [
                r'\b([a-z])\s*=\s*[^#\n]+',
                r'def\s+([a-z])\s*\(',
                r'class\s+([a-z])\s*:',
                r'([a-z])\s*:\s*[^=]+='
            ]
        else:
            var_patterns = [
                r'\b([a-z])\s*[:=]\s*[^;]+',
                r'function\s+([a-z])\s*\(',
                r'class\s+([a-z])\s*{'
            ]
        
        for line_num, line in enumerate(lines, 1):
            for pattern in var_patterns:
                matches = re.finditer(pattern, line)
                for match in matches:
                    var_name = match.group(1)
                    if len(var_name) <= 2:  # Very short variable names
                        issues.append({
                            "type": "generic_variable",
                            "message": f"Generic variable name '{var_name}' detected - Consider a more descriptive name",
                            "line": line_num,
                            "severity": "low",
                            "category": "ai_generated",
                            "suggestion": f"Rename '{var_name}' to something more descriptive",
                            "fix": self._generate_variable_name_fix(line, var_name, language)
                        })
        
        return issues

    def _check_descriptive_comments(self, code: str, language: str) -> List[Dict]:
        """Check for lack of descriptive comments"""
        issues = []
        lines = code.split('\n')
        
        # Count code lines vs comment lines
        code_lines = 0
        comment_lines = 0
        function_definitions = []
        
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped and not stripped.startswith(('#', '//', '/*', '*/')):
                code_lines += 1
                # Check for function/class definitions
                if re.search(r'\b(?:def|function|class)\s+\w+', stripped):
                    function_definitions.append((line_num, stripped))
            elif stripped.startswith(('#', '//', '/*')):
                comment_lines += 1
        
        # Check comment-to-code ratio
        if code_lines > 0 and comment_lines / code_lines < 0.1:
            issues.append({
                "type": "insufficient_comments",
                "message": f"Low comment density ({comment_lines}/{code_lines} lines) - AI-generated code often lacks descriptive comments",
                "line": 1,
                "severity": "medium",
                "category": "ai_generated",
                "suggestion": "Add more descriptive comments explaining the logic and purpose",
                "fix": self._generate_comment_fix(code, language)
            })
        
        # Check if functions have comments
        for line_num, func_line in function_definitions:
            has_comment = False
            # Check previous line for comment
            if line_num > 1:
                prev_line = lines[line_num - 2].strip()
                if prev_line.startswith(('#', '//', '/*')):
                    has_comment = True
            
            if not has_comment:
                issues.append({
                    "type": "function_without_comment",
                    "message": f"Function definition without descriptive comment: {func_line.strip()}",
                    "line": line_num,
                    "severity": "low",
                    "category": "ai_generated",
                    "suggestion": "Add a descriptive comment above the function",
                    "fix": self._generate_function_comment_fix(func_line, language)
                })
        
        return issues

    def _check_ai_markers(self, code: str) -> List[Dict]:
        """Check for explicit AI-generated markers"""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            for pattern in self.ai_patterns['ai_generated_markers']:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "ai_marker",
                        "message": f"AI-generated code marker detected: '{line.strip()}'",
                        "line": line_num,
                        "severity": "high",
                        "category": "ai_generated",
                        "suggestion": "Remove AI generation markers and review code quality",
                        "fix": ""  # Remove the line
                    })
                    break
        
        return issues

    def _check_code_timing(self, edit_history: List[Dict]) -> List[Dict]:
        """Check for large code blocks added at once (indicating AI generation)"""
        issues = []
        
        for edit in edit_history:
            if edit.get('type') == 'insert':
                text = edit.get('text', '')
                lines = text.split('\n')
                
                # If more than 10 lines were added at once, it might be AI-generated
                if len(lines) > 10:
                    issues.append({
                        "type": "large_code_block",
                        "message": f"Large code block ({len(lines)} lines) added at once - typical of AI-generated code",
                        "line": edit.get('line', 0),
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Review the code block for completeness and quality",
                        "fix": "Consider breaking down large code blocks into smaller, more manageable pieces"
                    })
        
        return issues

    def _check_generic_comments(self, code: str, language: str) -> List[Dict]:
        """Check for overly generic comments"""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            for pattern in self.ai_patterns['overly_generic_comments']:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "generic_comment",
                        "message": f"Generic comment detected: '{line.strip()}' - Add more specific details",
                        "line": line_num,
                        "severity": "low",
                        "category": "ai_generated",
                        "suggestion": "Make the comment more specific and descriptive",
                        "fix": self._generate_specific_comment_fix(line, language)
                    })
                    break
        
        return issues

    def _generate_suggestions(self, issues: List[Dict], ai_score: float) -> List[str]:
        """Generate general suggestions based on detected issues"""
        suggestions = []
        
        if ai_score > 0.5:
            suggestions.append("This code appears to be AI-generated. Consider reviewing for:")
            suggestions.append("- Completeness and functionality")
            suggestions.append("- Code quality and best practices")
            suggestions.append("- Security vulnerabilities")
            suggestions.append("- Performance optimizations")
        
        if any(issue['type'] == 'placeholder_comment' for issue in issues):
            suggestions.append("Replace placeholder comments with actual implementations")
        
        if any(issue['type'] == 'insufficient_comments' for issue in issues):
            suggestions.append("Add more descriptive comments to explain the code logic")
        
        if any(issue['type'] == 'generic_variable' for issue in issues):
            suggestions.append("Use more descriptive variable and function names")
        
        return suggestions

    def _generate_fixes(self, code: str, issues: List[Dict], language: str) -> List[Dict]:
        """Generate specific fixes for detected issues"""
        fixes = []
        
        for issue in issues:
            if 'fix' in issue and issue['fix']:
                fixes.append({
                    "type": issue['type'],
                    "line": issue['line'],
                    "original": issue.get('original', ''),
                    "fixed": issue['fix'],
                    "description": issue['suggestion']
                })
        
        return fixes

    def _generate_placeholder_fix(self, line: str, language: str) -> str:
        """Generate a fix for placeholder comments"""
        if language == 'python':
            return line.replace('TODO:', '# TODO: Implement this functionality')
        elif language in ['javascript', 'typescript']:
            return line.replace('TODO:', '// TODO: Implement this functionality')
        else:
            return line.replace('TODO:', '// TODO: Implement this functionality')

    def _generate_variable_name_fix(self, line: str, var_name: str, language: str) -> str:
        """Generate a fix for generic variable names"""
        # This is a simplified fix - in practice, you'd want more context
        if language == 'python':
            return line.replace(f'{var_name} =', f'{var_name}_data =')
        else:
            return line.replace(f'{var_name} =', f'{var_name}Data =')

    def _generate_comment_fix(self, code: str, language: str) -> str:
        """Generate a fix for insufficient comments"""
        if language == 'python':
            return "# Add descriptive comments here\n" + code
        else:
            return "// Add descriptive comments here\n" + code

    def _generate_function_comment_fix(self, func_line: str, language: str) -> str:
        """Generate a fix for functions without comments"""
        func_name = re.search(r'\b(?:def|function|class)\s+(\w+)', func_line)
        if func_name:
            name = func_name.group(1)
            if language == 'python':
                return f"# {name}: Add description of what this function does\n{func_line}"
            else:
                return f"// {name}: Add description of what this function does\n{func_line}"
        return func_line

    def _generate_specific_comment_fix(self, line: str, language: str) -> str:
        """Generate a fix for generic comments"""
        if language == 'python':
            return line.replace('This function', 'This function performs specific operation')
        else:
            return line.replace('This function', 'This function performs specific operation') 