import re
import ast
from typing import Dict, List, Any, Tuple
from datetime import datetime
import json

class AIGeneratedCodeDetector:
    def __init__(self):
        self.ai_patterns = {
            'placeholder_comments': [
                r'# TODO:.*',
                r'# FIXME:.*',
                r'# Insert.*here',
                r'# Add.*here',
                r'# Implement.*here',
                r'# Placeholder',
                r'// TODO:.*',
                r'// FIXME:.*',
                r'// Insert.*here',
                r'// Add.*here',
                r'// Implement.*here',
                r'// Placeholder',
                r'/\* TODO:.*?\*/',
                r'/\* FIXME:.*?\*/',
                r'/\* Insert.*?\*/',
                r'/\* Add.*?\*/',
                r'/\* Implement.*?\*/',
                r'/\* Placeholder.*?\*/'
            ],
            'generic_variable_names': [
                r'\bvar\s+[a-z]\b',
                r'\blet\s+[a-z]\b',
                r'\bconst\s+[a-z]\b',
                r'\b[a-z]\s*=\s*[^;]+',
                r'\b[a-z]\s*:\s*[^;]+',
                r'\b[a-z]\s*=\s*[^;]+',
                r'\b[a-z]\s*:\s*[^;]+'
            ],
            'ai_generated_markers': [
                r'Generated by AI',
                r'AI-generated',
                r'Model: GPT',
                r'AI completion',
                r'Generated by ChatGPT',
                r'Generated by Claude',
                r'Generated by Copilot',
                r'AI assistant',
                r'Generated by',
                r'This code was generated'
            ],
            'overly_generic_comments': [
                r'# This function',
                r'# This method',
                r'# This class',
                r'# This variable',
                r'// This function',
                r'// This method',
                r'// This class',
                r'// This variable'
            ]
        }
        
        self.descriptive_comment_patterns = [
            r'# [A-Z][^.]*\.',  # Comments that start with capital and end with period
            r'// [A-Z][^.]*\.',
            r'/\* [A-Z][^.]*\.',
            r'# [A-Z][^.]*:',   # Comments that start with capital and end with colon
            r'// [A-Z][^.]*:',
            r'/\* [A-Z][^.]*:'
        ]

    def detect_ai_generated_code(self, code: str, language: str, edit_history: List[Dict] = None) -> Dict[str, Any]:
        """
        Detect AI-generated code patterns and provide specific fixes
        """
        issues = []
        ai_score = 0.0
        total_checks = 0
        
        # Check for placeholder comments
        placeholder_issues = self._check_placeholder_comments(code, language)
        issues.extend(placeholder_issues)
        ai_score += len(placeholder_issues) * 0.3
        total_checks += 1
        
        # Check for generic variable names
        variable_issues = self._check_generic_variable_names(code, language)
        issues.extend(variable_issues)
        ai_score += len(variable_issues) * 0.2
        total_checks += 1
        
        # Check for lack of descriptive comments
        comment_issues = self._check_descriptive_comments(code, language)
        issues.extend(comment_issues)
        ai_score += len(comment_issues) * 0.25
        total_checks += 1
        
        # Check for AI-generated markers
        marker_issues = self._check_ai_markers(code)
        issues.extend(marker_issues)
        ai_score += len(marker_issues) * 0.5
        total_checks += 1
        
        # Check for large code blocks (timing analysis)
        if edit_history:
            timing_issues = self._check_code_timing(edit_history)
            issues.extend(timing_issues)
            ai_score += len(timing_issues) * 0.4
            total_checks += 1
        
        # Check for overly generic comments
        generic_comment_issues = self._check_generic_comments(code, language)
        issues.extend(generic_comment_issues)
        ai_score += len(generic_comment_issues) * 0.15
        total_checks += 1
        
        # Normalize AI score
        normalized_score = min(1.0, ai_score / max(total_checks, 1))
        
        return {
            "ai_detected": normalized_score > 0.3,
            "ai_confidence": normalized_score,
            "issues": issues,
            "suggestions": self._generate_suggestions(issues, normalized_score),
            "fixes": self._generate_fixes(code, issues, language)
        }

    def _check_placeholder_comments(self, code: str, language: str) -> List[Dict]:
        """Check for placeholder comments that indicate incomplete AI-generated code"""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            for pattern in self.ai_patterns['placeholder_comments']:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "placeholder_comment",
                        "message": f"Placeholder comment detected: '{line.strip()}' - This suggests incomplete AI-generated code",
                        "line": line_num,
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Replace placeholder with actual implementation or remove if not needed",
                        "fix": self._generate_placeholder_fix(line, language)
                    })
                    break
        
        return issues

    def _check_generic_variable_names(self, code: str, language: str) -> List[Dict]:
        """Check for overly generic variable names"""
        issues = []
        lines = code.split('\n')
        
        # Language-specific patterns
        if language in ['javascript', 'typescript']:
            var_patterns = [
                r'\b(?:var|let|const)\s+([a-z])\b',
                r'\b([a-z])\s*[:=]\s*[^;]+',
                r'function\s+([a-z])\s*\(',
                r'const\s+([a-z])\s*='
            ]
        elif language == 'python':
            var_patterns = [
                r'\b([a-z])\s*=\s*[^#\n]+',
                r'def\s+([a-z])\s*\(',
                r'class\s+([a-z])\s*:',
                r'([a-z])\s*:\s*[^=]+='
            ]
        else:
            var_patterns = [
                r'\b([a-z])\s*[:=]\s*[^;]+',
                r'function\s+([a-z])\s*\(',
                r'class\s+([a-z])\s*{'
            ]
        
        for line_num, line in enumerate(lines, 1):
            for pattern in var_patterns:
                matches = re.finditer(pattern, line)
                for match in matches:
                    var_name = match.group(1)
                    if len(var_name) <= 2:  # Very short variable names
                        issues.append({
                            "type": "generic_variable",
                            "message": f"Generic variable name '{var_name}' detected - Consider a more descriptive name",
                            "line": line_num,
                            "severity": "low",
                            "category": "ai_generated",
                            "suggestion": f"Rename '{var_name}' to something more descriptive",
                            "fix": self._generate_variable_name_fix(line, var_name, language)
                        })
        
        return issues

    def _check_descriptive_comments(self, code: str, language: str) -> List[Dict]:
        """Check for lack of descriptive comments"""
        issues = []
        lines = code.split('\n')
        
        # Count code lines vs comment lines
        code_lines = 0
        comment_lines = 0
        function_definitions = []
        
        for line_num, line in enumerate(lines, 1):
            stripped = line.strip()
            if stripped and not stripped.startswith(('#', '//', '/*', '*/')):
                code_lines += 1
                # Check for function/class definitions
                if re.search(r'\b(?:def|function|class)\s+\w+', stripped):
                    function_definitions.append((line_num, stripped))
            elif stripped.startswith(('#', '//', '/*')):
                comment_lines += 1
        
        # Check comment-to-code ratio
        if code_lines > 0 and comment_lines / code_lines < 0.1:
            issues.append({
                "type": "insufficient_comments",
                "message": f"Low comment density ({comment_lines}/{code_lines} lines) - AI-generated code often lacks descriptive comments",
                "line": 1,
                "severity": "medium",
                "category": "ai_generated",
                "suggestion": "Add more descriptive comments explaining the logic and purpose",
                "fix": self._generate_comment_fix(code, language)
            })
        
        # Check if functions have comments
        for line_num, func_line in function_definitions:
            has_comment = False
            # Check previous line for comment
            if line_num > 1:
                prev_line = lines[line_num - 2].strip()
                if prev_line.startswith(('#', '//', '/*')):
                    has_comment = True
            
            if not has_comment:
                issues.append({
                    "type": "function_without_comment",
                    "message": f"Function definition without descriptive comment: {func_line.strip()}",
                    "line": line_num,
                    "severity": "low",
                    "category": "ai_generated",
                    "suggestion": "Add a descriptive comment above the function",
                    "fix": self._generate_function_comment_fix(func_line, language)
                })
        
        return issues

    def _check_ai_markers(self, code: str) -> List[Dict]:
        """Check for explicit AI-generated markers"""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            for pattern in self.ai_patterns['ai_generated_markers']:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "ai_marker",
                        "message": f"AI-generated code marker detected: '{line.strip()}'",
                        "line": line_num,
                        "severity": "high",
                        "category": "ai_generated",
                        "suggestion": "Remove AI generation markers and review code quality",
                        "fix": ""  # Remove the line
                    })
                    break
        
        return issues

    def _check_code_timing(self, edit_history: List[Dict]) -> List[Dict]:
        """Check for large code blocks added at once (indicating AI generation)"""
        issues = []
        
        for edit in edit_history:
            if edit.get('type') == 'insert':
                text = edit.get('text', '')
                lines = text.split('\n')
                
                # If more than 10 lines were added at once, it might be AI-generated
                if len(lines) > 10:
                    issues.append({
                        "type": "large_code_block",
                        "message": f"Large code block ({len(lines)} lines) added at once - typical of AI-generated code",
                        "line": edit.get('line', 0),
                        "severity": "medium",
                        "category": "ai_generated",
                        "suggestion": "Review the code block for completeness and quality",
                        "fix": "Consider breaking down large code blocks into smaller, more manageable pieces"
                    })
        
        return issues

    def _check_generic_comments(self, code: str, language: str) -> List[Dict]:
        """Check for overly generic comments"""
        issues = []
        lines = code.split('\n')
        
        for line_num, line in enumerate(lines, 1):
            for pattern in self.ai_patterns['overly_generic_comments']:
                if re.search(pattern, line, re.IGNORECASE):
                    issues.append({
                        "type": "generic_comment",
                        "message": f"Generic comment detected: '{line.strip()}' - Add more specific details",
                        "line": line_num,
                        "severity": "low",
                        "category": "ai_generated",
                        "suggestion": "Make the comment more specific and descriptive",
                        "fix": self._generate_specific_comment_fix(line, language)
                    })
                    break
        
        return issues

    def _generate_suggestions(self, issues: List[Dict], ai_score: float) -> List[str]:
        """Generate general suggestions based on detected issues"""
        suggestions = []
        
        if ai_score > 0.5:
            suggestions.append("This code appears to be AI-generated. Consider reviewing for:")
            suggestions.append("- Completeness and functionality")
            suggestions.append("- Code quality and best practices")
            suggestions.append("- Security vulnerabilities")
            suggestions.append("- Performance optimizations")
        
        if any(issue['type'] == 'placeholder_comment' for issue in issues):
            suggestions.append("Replace placeholder comments with actual implementations")
        
        if any(issue['type'] == 'insufficient_comments' for issue in issues):
            suggestions.append("Add more descriptive comments to explain the code logic")
        
        if any(issue['type'] == 'generic_variable' for issue in issues):
            suggestions.append("Use more descriptive variable and function names")
        
        return suggestions

    def _generate_fixes(self, code: str, issues: List[Dict], language: str) -> List[Dict]:
        """Generate specific fixes for detected issues"""
        fixes = []
        
        for issue in issues:
            if 'fix' in issue and issue['fix']:
                fixes.append({
                    "type": issue['type'],
                    "line": issue['line'],
                    "original": issue.get('original', ''),
                    "fixed": issue['fix'],
                    "description": issue['suggestion']
                })
        
        return fixes

    def _generate_placeholder_fix(self, line: str, language: str) -> str:
        """Generate a fix for placeholder comments"""
        if language == 'python':
            return line.replace('TODO:', '# TODO: Implement this functionality')
        elif language in ['javascript', 'typescript']:
            return line.replace('TODO:', '// TODO: Implement this functionality')
        else:
            return line.replace('TODO:', '// TODO: Implement this functionality')

    def _generate_variable_name_fix(self, line: str, var_name: str, language: str) -> str:
        """Generate a fix for generic variable names"""
        # This is a simplified fix - in practice, you'd want more context
        if language == 'python':
            return line.replace(f'{var_name} =', f'{var_name}_data =')
        else:
            return line.replace(f'{var_name} =', f'{var_name}Data =')

    def _generate_comment_fix(self, code: str, language: str) -> str:
        """Generate a fix for insufficient comments"""
        if language == 'python':
            return "# Add descriptive comments here\n" + code
        else:
            return "// Add descriptive comments here\n" + code

    def _generate_function_comment_fix(self, func_line: str, language: str) -> str:
        """Generate a fix for functions without comments"""
        func_name = re.search(r'\b(?:def|function|class)\s+(\w+)', func_line)
        if func_name:
            name = func_name.group(1)
            if language == 'python':
                return f"# {name}: Add description of what this function does\n{func_line}"
            else:
                return f"// {name}: Add description of what this function does\n{func_line}"
        return func_line

    def _generate_specific_comment_fix(self, line: str, language: str) -> str:
        """Generate a fix for generic comments"""
        if language == 'python':
            return line.replace('This function', 'This function performs specific operation')
        else:
            return line.replace('This function', 'This function performs specific operation') 