#!/usr/bin/env python3
"""
Test script to demonstrate AI-generated code detection features
"""

import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from services.ai_detector import AIGeneratedCodeDetector

def test_ai_detection():
    """Test the AI detection with various sample code snippets"""
    
    detector = AIGeneratedCodeDetector()
    
    # Test 1: Code with placeholder comments (AI-generated pattern)
    placeholder_code = '''
def process_data(data):
    # TODO: Implement data processing logic
    # Insert validation here
    result = []
    for item in data:
        # Add error handling
        result.append(item * 2)
    return result
'''
    
    print("=== Test 1: Placeholder Comments ===")
    result = detector.detect_ai_generated_code(placeholder_code, 'python')
    print(f"AI Detected: {result['ai_detected']}")
    print(f"Confidence: {result['ai_confidence']:.2%}")
    print("Issues found:")
    for issue in result['issues']:
        print(f"  - {issue['type']}: {issue['message']}")
    print()
    
    # Test 2: Code with generic variable names
    generic_vars_code = '''
def calculate(x, y):
    z = x + y
    a = z * 2
    b = a / 3
    return b
'''
    
    print("=== Test 2: Generic Variable Names ===")
    result = detector.detect_ai_generated_code(generic_vars_code, 'python')
    print(f"AI Detected: {result['ai_detected']}")
    print(f"Confidence: {result['ai_confidence']:.2%}")
    print("Issues found:")
    for issue in result['issues']:
        print(f"  - {issue['type']}: {issue['message']}")
    print()
    
    # Test 3: Code with insufficient comments
    no_comments_code = '''
def fetch_user_data(user_id):
    response = requests.get(f"/api/users/{user_id}")
    if response.status_code == 200:
        return response.json()
    else:
        return None

def process_user_data(user_data):
    processed_data = {}
    for key, value in user_data.items():
        if isinstance(value, str):
            processed_data[key] = value.upper()
        else:
            processed_data[key] = value
    return processed_data
'''
    
    print("=== Test 3: Insufficient Comments ===")
    result = detector.detect_ai_generated_code(no_comments_code, 'python')
    print(f"AI Detected: {result['ai_detected']}")
    print(f"Confidence: {result['ai_confidence']:.2%}")
    print("Issues found:")
    for issue in result['issues']:
        print(f"  - {issue['type']}: {issue['message']}")
    print()
    
    # Test 4: Code with AI generation markers
    ai_marker_code = '''
# Generated by AI
# This code was generated by ChatGPT
def ai_generated_function():
    # This function performs a specific operation
    pass
'''
    
    print("=== Test 4: AI Generation Markers ===")
    result = detector.detect_ai_generated_code(ai_marker_code, 'python')
    print(f"AI Detected: {result['ai_detected']}")
    print(f"Confidence: {result['ai_confidence']:.2%}")
    print("Issues found:")
    for issue in result['issues']:
        print(f"  - {issue['type']}: {issue['message']}")
    print()
    
    # Test 5: Well-written code (should have low AI detection)
    good_code = '''
def calculate_discount_price(original_price: float, discount_percentage: float) -> float:
    """
    Calculate the final price after applying a discount.
    
    Args:
        original_price: The original price of the item
        discount_percentage: The discount percentage (0-100)
    
    Returns:
        The final price after discount
    
    Raises:
        ValueError: If discount_percentage is not between 0 and 100
    """
    if not 0 <= discount_percentage <= 100:
        raise ValueError("Discount percentage must be between 0 and 100")
    
    discount_amount = original_price * (discount_percentage / 100)
    final_price = original_price - discount_amount
    
    return round(final_price, 2)
'''
    
    print("=== Test 5: Well-Written Code ===")
    result = detector.detect_ai_generated_code(good_code, 'python')
    print(f"AI Detected: {result['ai_detected']}")
    print(f"Confidence: {result['ai_confidence']:.2%}")
    print("Issues found:")
    for issue in result['issues']:
        print(f"  - {issue['type']}: {issue['message']}")
    print()
    
    # Test 6: JavaScript code with AI patterns
    js_code = '''
// This function processes user data
function processUserData(userData) {
    let x = [];
    let y = {};
    
    // TODO: Add validation
    for (let i = 0; i < userData.length; i++) {
        x.push(userData[i]);
    }
    
    return x;
}
'''
    
    print("=== Test 6: JavaScript Code ===")
    result = detector.detect_ai_generated_code(js_code, 'javascript')
    print(f"AI Detected: {result['ai_detected']}")
    print(f"Confidence: {result['ai_confidence']:.2%}")
    print("Issues found:")
    for issue in result['issues']:
        print(f"  - {issue['type']}: {issue['message']}")
    print()

if __name__ == "__main__":
    test_ai_detection() 