import * as vscode from 'vscode';
import { AiDiagnosticsProvider } from './providers/diagnostics';
import { AiCodeActionProvider } from './providers/codeActions';
import { AiHoverProvider } from './providers/hover';
import { LocalAiService } from './services/localAi';
import { EditHistoryService } from './services/editHistoryService';
import { registerCommands } from './commands';
import { FeedbackService } from './services/feedbackService';
import { registerFeedbackCommand } from './commands/feedback';
import { FeedbackDashboard } from './webviews/dashboard';

export function activate(context: vscode.ExtensionContext) {
    const aiService = new LocalAiService();
    const editHistoryService = new EditHistoryService();
    const feedbackService = new FeedbackService(context);
    const diagnosticsProvider = new AiDiagnosticsProvider(aiService, feedbackService);
    const codeActionProvider = new AiCodeActionProvider();
    const hoverProvider = new AiHoverProvider(diagnosticsProvider);

    // Register commands - FIXED: Don't use spread operator with void
    registerCommands(context, aiService, diagnosticsProvider); // This now stands alone
    context.subscriptions.push(
        registerFeedbackCommand(context, feedbackService),
        vscode.commands.registerCommand('ai-code-review.showDashboard', () => {
            FeedbackDashboard.show(context, feedbackService);
        }),
        vscode.commands.registerCommand('ai-code-review.detectAI', async () => {
            const editor = vscode.window.activeTextEditor;
            if (editor) {
                const document = editor.document;
                const code = document.getText();
                const editHistory = editHistoryService.getEditHistory(document);
                
                try {
                    const result = await aiService.detectAI(code, editHistory);
                    showAIDetectionResults(result);
                } catch (error) {
                    vscode.window.showErrorMessage('Failed to detect AI-generated code');
                }
            }
        })
    );

    // Register providers
    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(
            { scheme: 'file' },
            codeActionProvider,
            { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
        ),
        vscode.languages.registerHoverProvider(
            { scheme: 'file' },
            hoverProvider
        ),
        diagnosticsProvider,
        editHistoryService
    );

    // Setup auto-detection
    setupAutoDetection(diagnosticsProvider, editHistoryService);
}

function setupAutoDetection(diagnosticsProvider: AiDiagnosticsProvider, editHistoryService: EditHistoryService) {
    vscode.workspace.onDidOpenTextDocument(document => {
        if (isLikelyAIGenerated(document.getText())) {
            promptForAnalysis(document);
        }
    });

    vscode.workspace.onDidChangeTextDocument(event => {
        const document = event.document;
        const editHistory = editHistoryService.getRecentEdits(document, 3000); // Last 3 seconds
        
        // Check for large code blocks that might be AI-generated
        const largeBlocks = editHistoryService.detectLargeCodeBlocks(document);
        if (largeBlocks.length > 0) {
            setTimeout(() => {
                promptForAIAnalysis(document, editHistory);
            }, 1000);
        }
        
        if (event.contentChanges.some(change => isLikelyAIGenerated(change.text))) {
            setTimeout(() => diagnosticsProvider.refresh(event.document), 300);
        }
    });
}

function isLikelyAIGenerated(text: string): boolean {
    const aiMarkers = [
        'Generated by AI',
        'AI-generated',
        'Model: GPT',
        'AI completion',
        'TODO:',
        'FIXME:',
        'Insert logic here',
        'Add implementation here'
    ];
    return aiMarkers.some(marker => text.includes(marker));
}

function promptForAnalysis(document: vscode.TextDocument) {
    vscode.window.showInformationMessage(
        'AI-generated code detected. Would you like to analyze it?',
        'Analyze', 'Ignore'
    ).then(choice => {
        if (choice === 'Analyze') {
            vscode.commands.executeCommand('ai-code-review.analyze');
        }
    });
}

function promptForAIAnalysis(document: vscode.TextDocument, editHistory: any[]) {
    vscode.window.showInformationMessage(
        'Large code block detected. This might be AI-generated. Would you like to analyze it?',
        'Analyze', 'Ignore'
    ).then(choice => {
        if (choice === 'Analyze') {
            vscode.commands.executeCommand('ai-code-review.detectAI');
        }
    });
}

function showAIDetectionResults(result: any) {
    const confidence = Math.round(result.ai_confidence * 100);
    const message = result.ai_detected 
        ? `AI-generated code detected with ${confidence}% confidence`
        : `No AI-generated code detected (${confidence}% confidence)`;
    
    const severity = result.ai_detected ? 'warning' : 'info';
    
    vscode.window.showInformationMessage(message, 'View Details', 'Apply Fixes').then(choice => {
        if (choice === 'View Details') {
            showAIDetectionDetails(result);
        } else if (choice === 'Apply Fixes') {
            applyAIFixes(result);
        }
    });
}

function showAIDetectionDetails(result: any) {
    const panel = vscode.window.createWebviewPanel(
        'aiDetectionDetails',
        'AI Detection Results',
        vscode.ViewColumn.One,
        {}
    );
    
    const html = `
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>AI Detection Results</title>
            <style>
                body { font-family: Arial, sans-serif; padding: 20px; }
                .issue { margin: 10px 0; padding: 10px; border-left: 4px solid #ff6b6b; background: #f8f9fa; }
                .suggestion { margin: 5px 0; color: #495057; }
                .fix { margin: 5px 0; color: #28a745; font-family: monospace; }
            </style>
        </head>
        <body>
            <h2>AI Detection Results</h2>
            <p><strong>AI Detected:</strong> ${result.ai_detected ? 'Yes' : 'No'}</p>
            <p><strong>Confidence:</strong> ${Math.round(result.ai_confidence * 100)}%</p>
            
            <h3>Issues Found:</h3>
            ${result.issues.map((issue: any) => `
                <div class="issue">
                    <strong>${issue.type}:</strong> ${issue.message}
                    ${issue.suggestion ? `<div class="suggestion">Suggestion: ${issue.suggestion}</div>` : ''}
                    ${issue.fix ? `<div class="fix">Fix: ${issue.fix}</div>` : ''}
                </div>
            `).join('')}
            
            <h3>Suggestions:</h3>
            <ul>
                ${result.suggestions.map((suggestion: string) => `<li>${suggestion}</li>`).join('')}
            </ul>
        </body>
        </html>
    `;
    
    panel.webview.html = html;
}

function applyAIFixes(result: any) {
    // This would apply the suggested fixes to the current document
    vscode.window.showInformationMessage('Fix application feature coming soon!');
}

export function deactivate() {}

/* Summary:
- Bootstraps your extension by wiring together services and providers.
- Registers UI integrations (hover, diagnostics, code actions).
- Adds background listeners to proactively detect AI-generated content.
- Provides interactive prompts to let the user trigger analysis.
 **/