import * as vscode from 'vscode';
import { AiDiagnosticsProvider } from './providers/diagnostics';
import { AiCodeActionProvider } from './providers/codeActions';
import { AiHoverProvider } from './providers/hover';
import { LocalAiService } from './services/localAi';
import { registerCommands } from './commands';
import { FeedbackService } from './services/feedbackService';
import { registerFeedbackCommand } from './commands/feedback';
import { FeedbackDashboard } from './webviews/dashboard';

export function activate(context: vscode.ExtensionContext) {
    const aiService = new LocalAiService();
    const feedbackService = new FeedbackService(context);
    const diagnosticsProvider = new AiDiagnosticsProvider(aiService, feedbackService);
    const codeActionProvider = new AiCodeActionProvider();
    const hoverProvider = new AiHoverProvider(diagnosticsProvider);

    // Register commands - FIXED: Don't use spread operator with void
    registerCommands(context, aiService, diagnosticsProvider); // This now stands alone
    context.subscriptions.push(
        registerFeedbackCommand(context, feedbackService),
        vscode.commands.registerCommand('ai-code-review.showDashboard', () => {
            FeedbackDashboard.show(context, feedbackService);
        })
    );

    // Register providers
    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(
            { scheme: 'file' },
            codeActionProvider,
            { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
        ),
        vscode.languages.registerHoverProvider(
            { scheme: 'file' },
            hoverProvider
        ),
        diagnosticsProvider
    );

    // Setup auto-detection
    setupAutoDetection(diagnosticsProvider);
}

function setupAutoDetection(diagnosticsProvider: AiDiagnosticsProvider) { /*  Defines a function that sets up event 
    listeners to automatically detect when AI-generated code appears. **/
    vscode.workspace.onDidOpenTextDocument(document => {
        if (isLikelyAIGenerated(document.getText())) {
            promptForAnalysis(document);
            /*  When a file is opened, checks if it appears to be AI-generated.
            If so, prompts the user to analyze it using the AI engine**/
        }
    });

    vscode.workspace.onDidChangeTextDocument(event => { /* When text is changed in a document:
        Checks if any inserted text looks AI-generated.
        If it does, schedules a delayed analysis using the diagnostics provider after 300ms. **/
        if (event.contentChanges.some(change => isLikelyAIGenerated(change.text))) {
            setTimeout(() => diagnosticsProvider.refresh(event.document), 300);
        }
    });
}

function isLikelyAIGenerated(text: string): boolean {
    /* A helper function that checks for specific phrases indicating AI-generated content.
        Returns true if any are found in the provided text. **/
    const aiMarkers = [
        'Generated by AI',
        'AI-generated',
        'Model: GPT',
        'AI completion'
    ];
    return aiMarkers.some(marker => text.includes(marker));
}

function promptForAnalysis(document: vscode.TextDocument) { /* Displays a message to the user when AI-generated code is detected **/
    vscode.window.showInformationMessage(
        'AI-generated code detected. Would you like to analyze it?',
        'Analyze', 'Ignore'
    ).then(choice => {
        if (choice === 'Analyze') {
            vscode.commands.executeCommand('ai-code-review.analyze');
        }
    }); /* 
    Shows an info popup with buttons “Analyze” or “Ignore”.
    If “Analyze” is selected, runs the ai-code-review.analyze command.
     **/
}

export function deactivate() {} /*  VS Code calls this when the extension is deactivated.
    No cleanup is needed here, but it’s defined for completeness.**/

/* Summary:
- Bootstraps your extension by wiring together services and providers.
- Registers UI integrations (hover, diagnostics, code actions).
- Adds background listeners to proactively detect AI-generated content.
- Provides interactive prompts to let the user trigger analysis.
 **/