import * as vscode from 'vscode';
import { AiDiagnosticsProvider } from './providers/diagnostics';
import { AiCodeActionProvider } from './providers/codeActions';
import { AiHoverProvider } from './providers/hover';
import { LocalAiService } from './services/localAi';
import { registerCommands } from './commands';

export function activate(context: vscode.ExtensionContext) {
    const aiService = new LocalAiService();
    const diagnosticsProvider = new AiDiagnosticsProvider(aiService);
    const codeActionProvider = new AiCodeActionProvider();
    const hoverProvider = new AiHoverProvider();

    // Register commands
    registerCommands(context, aiService, diagnosticsProvider);

    // Register providers
    context.subscriptions.push(
        vscode.languages.registerCodeActionsProvider(
            { scheme: 'file' },
            codeActionProvider,
            { providedCodeActionKinds: [vscode.CodeActionKind.QuickFix] }
        ),
        vscode.languages.registerHoverProvider(
            { scheme: 'file' },
            hoverProvider
        ),
        diagnosticsProvider
    );

    // Setup auto-detection
    setupAutoDetection(diagnosticsProvider);
}

function setupAutoDetection(diagnosticsProvider: AiDiagnosticsProvider) {
    vscode.workspace.onDidOpenTextDocument(document => {
        if (isLikelyAIGenerated(document.getText())) {
            promptForAnalysis(document);
        }
    });

    vscode.workspace.onDidChangeTextDocument(event => {
        if (event.contentChanges.some(change => isLikelyAIGenerated(change.text))) {
            setTimeout(() => diagnosticsProvider.refresh(event.document), 300);
        }
    });
}

function isLikelyAIGenerated(text: string): boolean {
    const aiMarkers = [
        'Generated by AI',
        'AI-generated',
        'Model: GPT',
        'AI completion'
    ];
    return aiMarkers.some(marker => text.includes(marker));
}

function promptForAnalysis(document: vscode.TextDocument) {
    vscode.window.showInformationMessage(
        'AI-generated code detected. Would you like to analyze it?',
        'Analyze', 'Ignore'
    ).then(choice => {
        if (choice === 'Analyze') {
            vscode.commands.executeCommand('ai-code-review.analyze');
        }
    });
}

export function deactivate() {}